"""Add PerceptionEvent table and relationships

Revision ID: cd6fd35470ac
Revises: e4eba9cfaa6f
Create Date: 2026-05-08 07:44:52.321689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'cd6fd35470ac'
down_revision: Union[str, None] = 'e4eba9cfaa6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perception_events',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('session_id', sa.TEXT(), nullable=False),
    sa.Column('source_type', sa.TEXT(), nullable=False),
    sa.Column('salience_score', sa.FLOAT(), nullable=False),
    sa.Column('fingerprint', pgvector.sqlalchemy.VECTOR(512), nullable=True),
    sa.Column('fingerprint_bq', sa.TEXT(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("id ~ '^[A-Za-z0-9_-]+$'", name='perception_event_id_format'),
    sa.CheckConstraint('length(id) = 21', name='perception_event_id_length'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perception_events_created_at'), 'perception_events', ['created_at'], unique=False)
    # op.create_index(op.f('ix_perception_events_fingerprint_bq'), 'perception_events', ['fingerprint_bq'], unique=False, postgresql_using='gin') # Disabled due to pg_trgm dependency
    op.create_index(op.f('ix_perception_events_fingerprint_hnsw'), 'perception_events', ['fingerprint'], unique=False, postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'fingerprint': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_perception_events_session_id'), 'perception_events', ['session_id'], unique=False)
    op.add_column('documents', sa.Column('perception_event_id', sa.TEXT(), nullable=True))
    op.create_index(op.f('ix_documents_perception_event_id'), 'documents', ['perception_event_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'perception_events', ['perception_event_id'], ['id'])
    op.add_column('messages', sa.Column('perception_event_id', sa.TEXT(), nullable=True))
    op.create_index(op.f('ix_messages_perception_event_id'), 'messages', ['perception_event_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'perception_events', ['perception_event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_perception_event_id'), table_name='messages')
    op.drop_column('messages', 'perception_event_id')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_perception_event_id'), table_name='documents')
    op.drop_column('documents', 'perception_event_id')
    op.drop_index(op.f('ix_perception_events_session_id'), table_name='perception_events')
    op.drop_index(op.f('ix_perception_events_fingerprint_hnsw'), table_name='perception_events')
    op.drop_index(op.f('ix_perception_events_fingerprint_bq'), table_name='perception_events')
    op.drop_index(op.f('ix_perception_events_created_at'), table_name='perception_events')
    op.drop_table('perception_events')
    # ### end Alembic commands ###